### ISSUE TITLE
When I click on the jump, I will report the error.

### ISSUE THREAD

**Issue by pangshangggg** [yalishizhude/RxWX#6]
formSubmit:()=>{
    rxwx.navigateTo({url: '../setTask/setTask'})
      .debounce(1000)
      .subscribe()
  }
error：Rx.js:8064 Uncaught (in promise) TypeError: this.durationSelector.call is not a function
    at DebounceSubscriber._next (Rx.js:8064)
    at DebounceSubscriber.Subscriber.next (Rx.js:631)
    at RxWX.js? [sm]:14
    at <anonymous>

**Comment by yalishizhude** [comment]
Operator "debounce" is used incorrectly.

An available solution:

```
import rxwx, { Rx } from '../../util/RxWX.js';
Page({
  navigate: new Rx.Subject(),
  onReady() {
    Rx.Observable.of().multicast(this.navigate)
      .debounceTime(1000)
      .switchMap(url => rxwx.navigateTo({
        url
      }))
      .subscribe()
  },
  open(e) {
    this.navigate.next('../setTask/setTask')
  }
});
```

**Comment by pangshangggg** [comment]
thirdScriptError
Cannot read property 'subscribe' of undefined;at pages/main/main page lifeCycleMethod onReady function
TypeError: Cannot read property 'subscribe' of undefined
    at EmptyObservable.ConnectableObservable._subscribe (http://127.0.0.1:58478/appservice/utils/Rx.js:10899:33)
    at EmptyObservable.Observable.subscribe (http://127.0.0.1:58478/appservice/utils/Rx.js:685:41)
    at DebounceTimeOperator.call (http://127.0.0.1:58478/appservice/utils/Rx.js:7859:23)
    at Observable.subscribe (http://127.0.0.1:58478/appservice/utils/Rx.js:682:22)
    at SwitchMapOperator.call (http://127.0.0.1:58478/appservice/utils/Rx.js:13103:23)
    at Observable.subscribe (http://127.0.0.1:58478/appservice/utils/Rx.js:682:22)
    at e.onReady (http://127.0.0.1:58478/appservice/pages/main/main.js:53:8)
    at e.<anonymous> (http://127.0.0.1:58478/appservice/__dev__/WAService.js:17:25368)
    at J (http://127.0.0.1:58478/appservice/__dev__/WAService.js:17:14633)
    at Function.<anonymous> (http://127.0.0.1:58478/appservice/__dev__/WAService.js:17:16796)

**Comment by yalishizhude** [comment]
@pangshangggg Please show me your code~

**Comment by TravisXie** [comment]
@pangshangggg because U R using the wrong operator,
Using `debounceTime` will fix it and do the job~
